kind: pipeline
name: default

steps:
  - name: build
    image: node:12.4.0
    commands:
      - /bin/bash ./build.sh build
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    when:
      event:
        - push

  - name: deploy
    image: hashicorp/terraform:0.11.12
    commands:
      # - cd terraform
      # - terraform init
      # - terraform apply --var "my_name=yancui" --var "file_name=test.zip" -auto-approve
      - /bin/bash ./build.sh deploy dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    when:
      event:
        - push