kind: pipeline
name: default

steps:
  - name: build
    image: node:12.4.0
    commands:
      - /bin/bash ./build.sh build
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    when:
      event:
        - push

  - name: deploy
    image: hashicorp/terraform
    commands:
      - /bin/bash ./build.sh deploy dev
    when:
      event:
        - push