kind: pipeline
name: default

steps:
  - name: deploy to dev
    image: node:12.4.0-alpine
    commands:
      - ./build.sh deploy dev
    when:
      event:
        - push

  - name: deploy
    image: jmccann/drone-terraform:5.2-0.11.11
    root_dir: terraform
    when:
      event:
        - push