kind: pipeline
name: default

steps:
  - name: build
    image: node:12.4.0
    commands:
      - apt-get update
      - apt-get -y install zip
      - apt-get -y install md5
      - /bin/bash ./build.sh build
    when:
      event:
        - push

  - name: deploy
    image: hashicorp/terraform
    commands:
      - /bin/bash ./build.sh deploy dev
    when:
      event:
        - push